
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wwjudpfzijrxvkqxbsem.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind3anVkcGZ6aWpyeHZrcXhic2VtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM2NDc5MzAsImV4cCI6MjA1OTIyMzkzMH0.DBdBbk_4wYuYf-Rmx7H0FdZ648-FTlhCDr1pKqf1u-o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Helper function to check database connection
export const checkDatabaseConnection = async () => {
  try {
    // Use the RPC function that is working correctly
    const { data: rpcData, error: rpcError, count } = await supabase
      .rpc('get_products_with_current_price', {}, { count: 'exact', head: true });
    
    console.log("RPC function connection test result:", { error: rpcError, count });
    
    if (rpcError) {
      console.error('Database connection error with RPC:', rpcError);
      return { connected: false, error: rpcError };
    }
    
    // If RPC test passes, we're good to go
    return { connected: true, count };
  } catch (err) {
    console.error('Unexpected error checking database:', err);
    return { connected: false, error: err };
  }
};
