
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wwjudpfzijrxvkqxbsem.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind3anVkcGZ6aWpyeHZrcXhic2VtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM2NDc5MzAsImV4cCI6MjA1OTIyMzkzMH0.DBdBbk_4wYuYf-Rmx7H0FdZ648-FTlhCDr1pKqf1u-o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Helper function to check database connection
export const checkDatabaseConnection = async () => {
  try {
    // First try a simple RPC call to test connection
    const { data: rpcData, error: rpcError } = await supabase
      .rpc('get_products_with_current_price', {}, { count: 'exact', head: true });
    
    if (!rpcError) {
      console.log('RPC connection successful');
      return { connected: true, data: rpcData };
    }
    
    // If RPC fails, try a direct table query as fallback
    console.log('RPC connection failed, trying direct table query...');
    const { data, error } = await supabase
      .from('product')
      .select('*')
      .limit(1);
    
    if (error) {
      console.error('Database connection error:', error);
      return { connected: false, error };
    }
    
    console.log('Direct table query successful');
    return { connected: true, data };
  } catch (err) {
    console.error('Unexpected error checking database:', err);
    return { connected: false, error: err };
  }
};
